DROP DATABASE MATERNIDADE
USE master

CREATE DATABASE MATERNIDADE
USE MATERNIDADE

CREATE TABLE MAE(
ID_MAE INT NOT NULL IDENTITY(1001,1),
NOME VARCHAR(60) NOT NULL,
lOUGRADOURO_ENDEREÇO VARCHAR(100) NOT NULL,
NUMERO_ENDERECO INT NOT NULL CHECK(NUMERO_ENDERECO <0),
CEP_ENDERECO CHAR(08) NOT NULL CHECK (CEP_ENDERECO=8),
COMPLEMENTO_ENDERECO VARCHAR(200) NOT NULL,
TELEFONE CHAR(10) NOT NULL CHECK (TELEFONE=10),
DATA_NASC DATE NOT NULL
PRIMARY KEY(ID_MAE)
)
GO
CREATE TABLE BEBE(
ID_BEBE INT NOT NULL IDENTITY(1,1),
NOME VARCHAR (60) NOT NULL,
DATA_NASC DATE NOT NULL DEFAULT(GETDATE()),
ALTURA DECIMAL(7,2) NOT NULL CHECK (ALTURA <0),
PESO DECIMAL (4,3) NOT NULL CHECK (PESO <0),
ID_MAE INT NOT NULL,
PRIMARY KEY(ID_BEBE),
FOREIGN KEY (ID_MAE) REFERENCES MAE (ID_MAE)
)
GO
CREATE TABLE MEDICO(
CRM_NUMERO INT NOT NULL,
CRM_UF CHAR(02) NOT NULL,
NOME VARCHAR(60) NOT NULL,
TELEFONE_CELULAR CHAR (11) CHECK (TELEFONE_CELULAR=11) UNIQUE,
ESPECIALIDADE VARCHAR(30) NOT NULL
PRIMARY KEY (CRM_NUMERO, CRM_UF)
)
GO
CREATE TABLE BEBE_MEDICO(
    BEBEID INT NOT NULL,
    CRM_NUMERO INT NOT NULL,
    CRM_UF CHAR(2) NOT NULL,
    FOREIGN KEY (BEBEID) REFERENCES BEBE(ID_BEBE),
    FOREIGN KEY (CRM_NUMERO, CRM_UF) REFERENCES MEDICO (CRM_NUMERO, CRM_UF)
)

